HOSTS:
  sut:
    roles:
      - agent
      - default
      - babag
      - babag-sender
      - babag-api
      - babag-smtp
    platform: ubuntu-xenial-amd64
    hypervisor: vagrant
    box: puppetlabs/ubuntu-16.04-64-nocm
  rabbitmq:
    roles:
      - rabbitmq
    platform: ubuntu-precise-i386
    hypervisor: vagrant
    box: naphatkrit/rabbitmq
  postgres:
    roles:
      - postgres
    platform: ubuntu-precise-i386
    hypervisor: vagrant
    box: mbr/postgres
CONFIG:
type: foss
